#!/usr/bin/env bash
#installingi load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5699-webs
    bind *:80
    mode http
    balance roundrobin
    server 5854-web-01 35.172.200.53:80 check
    server 5854-web-02 54.87.32.168:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
