#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get  install  -y nginx

ufw allow "Nginx HTTP"

echo "Hoberlton School" > | sudo tee  /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo service nginx restart
